# Generated by Django 5.0.6 on 2024-05-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_attendee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
